backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: portfolio
    label: Portfolio
    path: static/CMS/portfolio/{{slug}}.md

    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: image, label: Image, widget: image, required: true }
      - { name: body, label: Body, widget: markdown }